import { Box, styled } from '@mui/material';

// eslint-disable-next-line react-refresh/only-export-components
export default styled(Box)(({ theme }) => ({
	width: '188px',
	minHeight: '248px',
	borderRadius: '10px',
	position: 'fixed',
	bottom: 20,
	left: 110,
	transform: 'translate(-50%)',
	background: theme.palette.background.darkBlue,

	'&::before': {
		content: '""',
		position: 'absolute',
		height: '160px',
		width: '160px',
		borderRadius: '50%',
		top: '-100px',
		left: '-94px',
		background: theme.palette.background.lightWhite,
	},
	'&::after': {
		content: '""',
		position: 'absolute',
		height: '160px',
		width: '160px',
		borderRadius: '50%',
		bottom: '-100px',
		right: '-94px',
		background: theme.palette.background.lightWhite,
	},
	'& .icon': {
		background: theme.palette.background.darkBlue,
		height: '48px',
		width: '48px',
		borderRadius: '50%',
		left: '50%',
		top: '-50%',
		border: '4px solid white',
		transform: 'translate(-50%,-50%)',
	},
	'& .button': {
		marginTop: '3rem',
		padding: 0,
		fontWeight: 600,
		color: 'black',
		fontSize: '12px',
		background: 'white',
		height: '40px',
		width: '156px',
		borderRadius: '10px',
		left: '50%',
		transform: 'translate(-50%)',
	},
}));
